### ISSUE TITLE
[desktop] : can't specify the K8s config file 

### ISSUE THREAD

**Issue by sgandon** [kinvolk/headlamp#357]
## Description
I am using many different K8s config files with only one context in them but headlamp seems to be using the default ~/.kube.config file.
That would be nice to be able to choose the config file.

## Impact

can use headlamp if i have to copy my individual config files to the default `config` file.

**Comment by joaquimrocha** [comment]
Thanks @sgandon .
Improving the initial setup experience is in our list. As a quick fix, I think we can make it so that all kube config files within a Headlamp's config folder, as well as exposing the `-kubeconfig` option we have in the backend.

If you need a dirtier approach, you can run the backend with the mentioned option (`./backend/server -dev -kubeconfig /your/config`), and still use the downloaded app for launching the UI.

**Comment by sgandon** [comment]
In fact your proposal for reading all kube configs from a folder is great as all my config files are located in the default K8s config folder. So I would suggest you use the ~/.kube folder instead of the Headlamp's config folder.
