### ISSUE TITLE
Desktop App Closed without Quit Golang Server

### ISSUE THREAD

**Issue by lijianzhi01** [kinvolk/headlamp#476]
## Description

I closed my desktop app, but golang server still running behind the scenes.

## Impact

Memory Leak

**Comment by illume** [comment]
We've struggled with this before, but thought that at least the server.exe was being killed properly on shutdown with the app now.

The related issue about handling this case is here: https://github.com/kinvolk/headlamp/issues/397 That issue is more about offering a way for the user to deal with it, so I think this issue should remain open.

**Comment by illume** [comment]
This has been addressed some further PRs a while ago. https://github.com/kinvolk/headlamp/issues/397 is still open to handle the remaining issues.

@lijianzhi01 I'm closing this, but if you feel it's still an issue please let me know and I'll reopen?
